---
- name: Installing and Launching Auditbeat
  hosts: appservers
  become: yes
  tasks:
    # Use curl module to download the latest version of Audittbeat
  - name: Download Auditbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.17.0-amd64.deb
    
    # Use dpkg module to install Auditbeat
  - name: Install Auditbeat .deb
    command: dpkg -i auditbeat-8.17.0-amd64.deb

    # Use copy module to copy and drop Auditbeat yaml file from Ansible into Auditbeat configuration
  - name: Drop in auditbeat.yml
    copy:
      src: /etc/ansible/auditbeat-config.yml
      dest: /etc/auditbeat/auditbeat.yml

    # Use setup module to configure Auditbeat
  - name: Setup Auditbeat
    command: auditbeat setup

    # Use start module to start Auditbeat service
  - name: Start Auditbeat service
    command: service auditbeat-elastic start

    # Use systemd module to enable auditbeat upon boot
  - name: Enable auditbeat service on boot
    systemd:
      name: auditbeat-elastic
      enabled: yes
