---
# This Playbook file automates the data backup and installation of wordpress.
# This is a remediation for patching and updating the vulnerable WordPress application from the Security Assessment.
- Name: WordPress Update
   hosts: localhost
   connection: local
   tasks:
  # Use stop httpd module to halt the wordpress service
    - name: stop httpd
      systemd:
        name: httpd
        state: stopped
      become: true

    # Backup module for data backup and archiving for WordPress service & database
    - name: backup html files
      archive:
        path: /var/www/html
        #You can update the destination with your directory where html files are located
        dest: "/home/centos/backups/wordpress-bck-{{ansible_date_time.iso8601_basic_short}}.tgz"
        format: gz
      become: true

    - name: backup wordpress database
      command: /etc/backup-wpdb.sh
      become: true

    # Get module for downloading latest version of WordPress
    - name: get latest wordpress
      unarchive:
        src:  https://wordpress.org/latest.zip
        dest: /tmp/
        remote_src: yes
      become: true

    # Wait module for halting any additional commands until WordPress successfully downloads
    - name: Wait until wordpress has been downloaded
      wait_for:
        path: /tmp/wordpress/index.php
        state: present

    # Copy module for moving WordPress to website
    - name: copy wordpress to website
      shell: /bin/cp -rf /tmp/wordpress/* /var/www/html/
      become: true

    # Module deletes temporary downloaded folder after WordPress installation
    - name: delete tmp wordpress
      file:
        path: /tmp/wordpress
        state: absent
      become: true

    # Module restarts WordPress service
    - name: start httpd
      systemd: 
        name: httpd
        state: started
        daemon_reload: yes
      become: true

# Sudo command for running script: sudo ansible-playbook -v update-wordpress.yml